# Generated by Django 5.1.4 on 2024-12-20 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_userlikepost_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='https://cdn.business2community.com/wp-content/uploads/2017/08/blank-profile-picture-973460_640.png', upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='userlikepost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_post', to='blog.post'),
        ),
    ]
