# Generated by Django 5.1.4 on 2024-12-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_profile_picture_alter_userlikepost_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='media/posts/boyy.jpg.url', upload_to='profile/'),
        ),
    ]
