# Generated by Django 5.1.4 on 2024-12-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='media/posts/boyy.jpg', upload_to='profile/'),
        ),
    ]
