# Generated by Django 5.1.4 on 2024-12-20 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='/posts/boyy.jpg', upload_to='profile/'),
        ),
    ]
